#! /usr/bin/env perl

use v5.36;
use Path::Tiny;

my %files = (
  google => path( 'GoogleSafeSearch.hosts' ) ,
  pihole => path( '~/etc-pihole/custom.list' ) ,
);

say 'Contents appended successfully'
  if $files{pihole} -> append( $files{google} -> lines ); # returns 1
