#! /usr/bin/env perl

use v5.36;
use Path::Tiny;

my %files = (
  google => path( 'GoogleSafeSearch.hosts' ) ,
  pihole => path( '~/etc-pihole/custom.list' ) ,
);

my $append = $files{pihole} -> append( $files{google} -> lines );

# User information
if ( $append == 1 ) {
  say 'Contents appended successfully'
}
else {
  say 'There was a problem appending to the file'
}
